version: '3.8'

networks:
  spendsense-net:
    driver: bridge

services:

  mysql-expenses:
    image: mysql:latest
    container_name: mysql-expense-1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expense_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - spendsense-net

  mysql-keycloak:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - spendsense-net

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik Dashboard
      - "443:443"    # HTTPS (optional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - spendsense-net


  expense-service:
    build: ./expense-service/openjdk
    container_name: expense-service-1

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.expense-service.rule=Host(`local.spendsense.net`)"
      - "traefik.http.routers.expense-service.entrypoints=web"
      - "traefik.http.services.expense-service.loadbalancer.server.port=8080"

    networks:
      - spendsense-net


volumes:
  mysql_data: