version: '3.8'

networks:
  spendsense-net:
    driver: bridge

services:

  mysql-expenses:
    image: mysql:latest
    container_name: mysql-expense-1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expense_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - spendsense-net

  mysql-keycloak:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - spendsense-net

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik Dashboard
      - "443:443"    # HTTPS (optional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - spendsense-net

  keycloak:
    image: keycloak/keycloak:latest
    command: start-dev --log=console,file
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql-keycloak
      KC_DB_URL_PORT: 3306
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_PORT: 8888

      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_SAMESITE: "Lax"  # Или "None" ако е нужно
      OAUTH2_PROXY_COOKIE_DOMAINS: ".local.spendsense.net"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.local.spendsense.net`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8888"

    ports:
      - "8888:8888"
    depends_on:
      - mysql-keycloak
    networks:
      - spendsense-net


  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    ports:
      - "4180:4180"
    networks:
      - spendsense-net

    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_OIDC_ISSUER_URL: "http://auth.local.spendsense.net/realms/master"
      OAUTH2_PROXY_COOKIE_SECRET: "i6OQu7IbTqFNdNdqQQivBLJO74a5GEXM"
      OAUTH2_PROXY_CLIENT_ID: "spendsense-client"
      OAUTH2_PROXY_CLIENT_SECRET: "vbm8bGCQ3lNAp7esnzu3zJR0O1U0FuaT"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_REDIRECT_URL: "http://local.spendsense.net/oauth2/callback"
      OAUTH2_PROXY_UPSTREAMS: "http://expense-service:8080"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"

    extra_hosts:
      "auth.local.spendsense.net": host-gateway

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth2-proxy.rule=Host(`local.spendsense.net`) && (PathPrefix(`/api/expenses`) || PathPrefix(`/oauth2`))"
      - "traefik.http.routers.oauth2-proxy.entrypoints=web"
      - "traefik.http.routers.oauth2-proxy.service=oauth2-proxy-service"
      - "traefik.http.services.oauth2-proxy-service.loadbalancer.server.port=4180"

    depends_on:
      - keycloak
    restart:
      on-failure

  expense-service:
    build: ./expense-service/openjdk
    container_name: expense-service

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.expense-service.rule=Host(`local.spendsense.net`)"
      - "traefik.http.routers.expense-service.entrypoints=web"
      - "traefik.http.services.expense-service.loadbalancer.server.port=8080"

    networks:
      - spendsense-net


volumes:
  mysql_data:

