version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-expenses
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expense_db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - expenses-network

  expense-service:
    build:
      context: ./
      dockerfile: openjdk/Dockerfile
    container_name: expense-service
    restart: always
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-expenses:3306/expenses_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - expenses-network

volumes:
  mysql_data:

networks:
  expenses-network:
    driver: bridge